# Generated by Django 6.0.7 on 2026-07-22 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(help_text='Name of the ward (e.g., Cardiac ICU, Pediatrics Wing A).', max_length=150, verbose_name='Ward Name')),
                ('capacity', models.IntegerField(help_text='Maximum number of beds in this ward (1-500).', validators=[django.core.validators.MinValueValidator(1, message='Ward capacity must be at least 1 bed.'), django.core.validators.MaxValueValidator(500, message='Ward capacity cannot exceed 500 beds.')], verbose_name='Capacity (Beds)')),
                ('hospital', models.ForeignKey(help_text='The hospital facility this ward belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='hospitals.hospital', verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['ward_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0), ('capacity__lte', 500)), name='check_ward_capacity_valid')],
            },
        ),
    ]
