# Generated by Django 6.0.7 on 2026-07-22 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['-updated_at', 'ward_name'], 'verbose_name': 'Ward', 'verbose_name_plural': 'Wards'},
        ),
        migrations.AddField(
            model_name='ward',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='ward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
