# Generated by Django 6.0.7 on 2026-07-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDirector',
            fields=[
                ('director_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('director_name', models.CharField(help_text='Full name of the medical director (e.g., Dr. Sarah Jenkins).', max_length=150, verbose_name='Director Name')),
                ('qualification', models.CharField(help_text='Academic/Medical qualifications (e.g., MD, PhD, MHA).', max_length=200, verbose_name='Qualification')),
                ('hospital', models.OneToOneField(help_text='The hospital facility assigned to this director.', on_delete=django.db.models.deletion.CASCADE, related_name='director', to='hospitals.hospital', verbose_name='Assigned Hospital')),
            ],
            options={
                'verbose_name': 'Hospital Director',
                'verbose_name_plural': 'Hospital Directors',
                'ordering': ['director_name'],
            },
        ),
    ]
