# Generated by Django 6.0.7 on 2026-07-22 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(help_text='Unique name of the hospital facility.', max_length=200, unique=True, verbose_name='Hospital Name')),
                ('location', models.CharField(help_text='City/Region location of the hospital.', max_length=255, verbose_name='Location')),
                ('founded_year', models.IntegerField(help_text='Year the hospital was established (between 1800 and present).', validators=[django.core.validators.MinValueValidator(1800, message='Founded year cannot be before 1800.'), django.core.validators.MaxValueValidator(2026, message='Founded year cannot be in the future.')], verbose_name='Founded Year')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['hospital_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('founded_year__gte', 1800), ('founded_year__lte', 2026)), name='check_founded_year_valid')],
            },
        ),
    ]
